<?php
return['form1'=>'<form method="post"><input name="firstNum" ><input name="secondNum"><input type="submit"></form><br><br>',
    'hrefTest'=>'<br><a href="test.php">Страница test.php</a><br>',
    'countryUser'=> '<br><form method="post"><input name="usersCountry" placeholder="Введите страну" ><input type="submit"></form><br><br>',
    'factNum'=>'<br><form method="post"><input name="factNum" placeholder="Введите число" ><input type="submit"></form><br><br>',
  ];

?>


