<?php
session_start();

return['form1'=>'<form method="post"><input name="firstNum" ><input name="secondNum"><input type="submit"></form><br><br>',
    'hrefNext'=>'<br><a href="next.php">Следующая страница</a><br>',
    'hrefIndex'=>'<br><a href="index.php">Страница index.php</a><br>',
    'hrefTest'=>'<br><a href="test.php">Страница test.php</a><br>',
    'countryUser'=> '<br><form method="post"><input name="usersCountry" placeholder="Введите страну" ><input type="submit"></form><br><br>',
    'usersMail'=> '<br><form method="post"><input name="usersMail" placeholder="Введите email" ><input type="submit"></form><br><br>',
    'usersBDay'=>'<br><form method="post"><input name="usersBDay" placeholder="Введите дату рождения" ><input type="submit"></form><br><br>',
    ];