<?php
return['form1'=>"<form method='post'><input name ='yearToJan' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form2'=>"<form method='post'><input name ='yearType' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form3'=>"<form method='post'><input name ='dateWeekDay' PLACEHOLDER='введите дату'><input type='submit' value='Отправить'></form><br>",
    'form4'=>"<form method='post'><input name ='birthDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form5'=>"<form method='post'><input name ='birthZodiacDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form6'=>"<form method='post'><textarea name ='countSymb' ></textarea><br><input type='submit' value='Отправить'></form><br>",
    'form7'=>"<form method='post'><input name ='searchLetters' PLACEHOLDER='Введите буквы'><br><input type='submit' value='Отправить'></form><br>",
    'form8'=>"<form method='post'><textarea name ='sortWords' ></textarea><br><input type='submit' value='Отправить'></form><br>",
     'form9'=>"<form method='post'><input name ='translett' PLACEHOLDER='Введите слово'><br><input type='submit' value='Отправить'></form><br>",
     'form10'=>"<form method='post'><input name ='strToTranslettAfterChoose' PLACEHOLDER='Введите слово'><br><input type='radio' name='translett' value='rusToEn'><label>транслит</label><br><input type='radio' name='translett' value='enToRus'><label>детранслит</label><br><input type='submit' value='Отправить'></form><br>",
    'form11'=>"<form method='post'><input name='a' placeholder='a'><input name='b' placeholder='b'><input name='c' placeholder='c'><input type='submit' value='Отправить'></form><br><br>",
        'form12'=>"<form method='post'><input name='firstNum' placeholder='Первое число'><input name='secondNum' placeholder='Второе число'><input name='thirdNum' placeholder='Третье число'><input type='submit' value='Отправить'></form><br><br>",
    'form13'=>"<form method='post'><input name ='numToDenominators' PLACEHOLDER='введите число'><input type='submit' value='Отправить'></form><br>",
    'form14'=>"<form method='post'><input name ='numToDecomp' PLACEHOLDER='введите число'><input type='submit' value='Отправить'></form><br>",
    'form15'=>"<form method='post'><input name ='firstNODnum' PLACEHOLDER='введите число'><input name ='secondNODnum' PLACEHOLDER='введите число'><input type='submit' value='Отправить'></form><br>",
    'form16'=>"<form method='post'><input name ='firstNOKnum' PLACEHOLDER='введите число'><input name ='secondNOKnum' PLACEHOLDER='введите число'><input type='submit' value='Отправить'></form><br>",
    'form17'=>"<form method='post'>
                    <select name='day'>
                        <option value='1'>1</option>
                        <option value='2'>2</option>
                        <option value='3'>3</option>
                        <option value='4'>4</option>
                        <option value='5'>5</option>
                        <option value='6'>6</option>
                        <option value='7'>7</option>
                        <option value='8'>8</option>
                        <option value='9'>9</option>
                        <option value='10'>10</option>
                        <option value='11'>11</option>
                        <option value='12'>12</option>
                        <option value='13'>13</option>
                        <option value='14'>14</option>
                        <option value='15'>15</option>
                        <option value='16'>16</option>
                        <option value='17'>17</option>
                        <option value='18'>18</option>
                        <option value='19'>19</option>
                        <option value='20'>20</option>
                        <option value='21'>21</option>
                        <option value='22'>22</option>
                        <option value='23'>23</option>
                        <option value='24'>24</option>
                        <option value='25'>25</option>
                        <option value='26'>26</option>
                        <option value='27'>27</option>
                        <option value='28'>28</option>
                        <option value='29'>29</option>
                        <option value='30'>30</option>
                        <option value='31'>31</option>
                    </select>
                    <select name='month'>
                        <option value='январь'>январь</option>
                        <option value='февраль'>февраль</option>
                        <option value='март'>март</option>
                        <option value='апрель'>апрель</option>
                        <option value='май'>май</option>
                        <option value='июнь'>июнь</option>
                        <option value='июль'>июль</option>
                        <option value='август'>август</option>
                        <option value='сентябр'>сентябрь</option>
                        <option value='оетябрь'>оетябрь</option>
                        <option value='ноябрь'>ноябрь</option>
                        <option value='декабрь'>декабрь</option>
                    </select>
                    <select name='year'>
                        <option value='1990'>1990</option>
                        <option value='1991'>1991</option>
                        <option value='1992'>1992</option>
                        <option value='1993'>1993</option>
                        <option value='1994'>1994</option>
                        <option value='1995'>1995</option>
                        <option value='1996'>1996</option>
                        <option value='1997'>1997</option>
                        <option value='1998'>1998</option>
                        <option value='1999'>1999</option>
                        <option value='2000'>2000</option>
                        <option value='2001'>2001</option>
                        <option value='2002'>2002</option>
                        <option value='2003'>2003</option>
                        <option value='2004'>2004</option>
                        <option value='2005'>2005</option>
                        <option value='2006'>2006</option>
                        <option value='2007'>2007</option>
                        <option value='2008'>2008</option>
                        <option value='2009'>2009</option>
                        <option value='2010'>2010</option>
                        <option value='2011'>2011</option>
                        <option value='2012'>2012</option>
                        <option value='2013'>2013</option>
                        <option value='2014'>2014</option>
                        <option value='2015'>2015</option>
                        <option value='2016'>2016</option>
                        <option value='2017'>2017</option>
                        <option value='2018'>2018</option>
                        <option value='2019'>2019</option>
                        <option value='2020'>2020</option>
                        <option value='2021'>2021</option>
                        <option value='2022'>2022</option>
                        <option value='2023'>2023</option>
                        <option value='2024'>2024</option>
                        <option value='2025'>2025</option>
                    </select><input type='submit' value='Отправить'></form><br>
                    </form>",
      ];
