<?php
return['form1'=>"<form method='post'><input name ='yearToJan' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form2'=>"<form method='post'><input name ='yearType' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form3'=>"<form method='post'><input name ='dateWeekDay' PLACEHOLDER='введите дату'><input type='submit' value='Отправить'></form><br>",
    'form4'=>"<form method='post'><input name ='birthDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form5'=>"<form method='post'><input name ='birthZodiacDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form6'=>"<form method='post'><textarea name ='countSymb' ></textarea><br><input type='submit' value='Отправить'></form><br>",
    'form7'=>"<form method='post'><input name ='searchLetters' PLACEHOLDER='Введите буквы'><br><input type='submit' value='Отправить'></form><br>",
    'form8'=>"<form method='post'><textarea name ='sortWords' ></textarea><br><input type='submit' value='Отправить'></form><br>",
     'form9'=>"<form method='post'><input name ='translett' PLACEHOLDER='Введите слово'><br><input type='submit' value='Отправить'></form><br>",
     'form10'=>"<form method='post'><input name ='strToTranslettAfterChoose' PLACEHOLDER='Введите слово'><br><input type='radio' name='translett' value='rusToEn'><label>транслит</label><br><input type='radio' name='translett' value='enToRus'><label>детранслит</label><br><input type='submit' value='Отправить'></form><br>",
    'form11'=>"<form method='post'><input name='a' placeholder='a'><input name='b' placeholder='b'><input name='c' placeholder='c'><input type='submit' value='Отправить'></form><br><br>",
];
