<?php
return['form1'=>"<form method='post'><input name ='yearToJan' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form2'=>"<form method='post'><input name ='yearType' PLACEHOLDER='введите год'><input type='submit' value='Отправить'></form><br>",
    'form3'=>"<form method='post'><input name ='dateWeekDay' PLACEHOLDER='введите дату'><input type='submit' value='Отправить'></form><br>",
    'form4'=>"<form method='post'><input name ='birthDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form5'=>"<form method='post'><input name ='birthZodiacDate' PLACEHOLDER='введите дату рождения'><input type='submit' value='Отправить'></form><br>",
    'form6'=>"<form method='post'><textarea name ='countSymb' ></textarea><br><input type='submit' value='Отправить'></form><br>",
];
