<?php
$nameUser = $_GET['nameUser'] ??'';
$nameUserAgain=$_GET['nameUserAgain']??'';
$userMessage =$_GET['userMessage']??'';
return ['form1' => "
<form action = '' method='get'>
<input placeholder='Введите имя' name = 'name'> 
<input type='submit' value = 'Отправить'>
</form>
",'form2'=>"
<form action = '' method='get'>
<input placeholder='Введите имя' name = 'userName'> 
<input placeholder='Введите возраст' name = 'userAge'> <br><br>
<textarea name = 'message' placeholder='Введите ваше сообщение'></textarea><br><br>
<input type='submit' value = 'Отправить'>
</form>
",'form3' => "
<form action = '' method='get'>
<input placeholder='Введите возраст' name = 'age'> <br><br>
<input type='submit' value = 'Отправить'>
</form>
", 'form4'=> "
    <form action = '' method='get'>
<input placeholder='Введите логин' name = 'login'> <br><br>
<input placeholder='Введите пароль' type='password' name = 'password'> <br><br>
<input type='submit' value = 'Отправить'>
</form>
",'form5'=>"
<form action = '' method='get'>
<input placeholder='Введите имя'  name = 'nameUser'>
<input type='submit' value = 'Отправить'>
</form>
", 'form6'=>"
<form action = '' method='get'>
<input placeholder='Введите имя'  name = 'nameUser' value='$nameUser'>
<input type='submit' value = 'Отправить'>
</form>
", 'form7'=>"
<form action = '' method='get'>
<input placeholder='Введите имя'  name = 'nameUserAgain'><br>
<textarea name ='userMessage'></textarea><br>
<input type='submit' value = 'Отправить'>
</form>
",'form8'=>"
<form action = '' method='get'>
<input placeholder='Введите имя'  name = 'nameUserAgain' value=$nameUserAgain><br>
<textarea name ='userMessage'>$userMessage</textarea><br>
<input type='submit' value = 'Отправить'>
</form>
" ];